version: "3.9"
services:

  ruby:
    build: 
      dockerfile: ./docker/dockerfile-ruby
      context: ./
    volumes:
      - './site:/site'
    ports:
      - '4001:4000'
    command: bundle exec jekyll serve --host 0.0.0.0.0 --trace