version: "3.9"
services:

  ruby:
    build: 
      dockerfile: ./docker/dockerfile-ruby
      context: ./
    volumes:
      - './docs:/docs'
    ports:
      - '4001:4000'
    command: bundle exec jekyll serve --trace --host 0.0.0.0
    extra_hosts:
      localhost: 127.0.0.1
